#ifndef __BSP_DMA_DEFINE_H
#define __BSP_DMA_DEFINE_H

#include "BSP_USART.h"

#define NO_FLAG 0

BSP_USART_Typedef BSP_DMA_USART1_TX	= {__DMA1,TX_MODE,DMA1_Channel4,USART1,DMA1_FLAG_TC4,DMA1_FLAG_HT4};
BSP_USART_Typedef BSP_DMA_USART2_TX	= {__DMA1,TX_MODE,DMA1_Channel7,USART2,DMA1_FLAG_TC7,DMA1_FLAG_HT7};
BSP_USART_Typedef BSP_DMA_USART3_TX	= {__DMA1,TX_MODE,DMA1_Channel2,USART3,DMA1_FLAG_TC2,DMA1_FLAG_HT2};
BSP_USART_Typedef BSP_DMA_UART4_TX	= {__DMA2,TX_MODE,DMA2_Channel5,UART4,DMA2_FLAG_TC5,DMA2_FLAG_HT5};
BSP_USART_Typedef BSP_DMA_UART5_TX	= {__NO_DMA,TX_MODE,NULL,UART5,NO_FLAG,NO_FLAG};
	

BSP_USART_Typedef BSP_DMA_USART1_RX	= {__DMA1,RX_MODE,DMA1_Channel5,USART1,DMA1_FLAG_TC5,DMA1_FLAG_HT5};
BSP_USART_Typedef BSP_DMA_USART2_RX	= {__DMA1,RX_MODE,DMA1_Channel6,USART2,DMA1_FLAG_TC6,DMA1_FLAG_HT6};
BSP_USART_Typedef BSP_DMA_USART3_RX	= {__DMA1,RX_MODE,DMA1_Channel3,USART3,DMA1_FLAG_TC3,DMA1_FLAG_HT3};
BSP_USART_Typedef BSP_DMA_UART4_RX	= {__DMA2,RX_MODE,DMA2_Channel3,UART4,DMA2_FLAG_TC3,DMA2_FLAG_HT3};
BSP_USART_Typedef BSP_DMA_UART5_RX	= {__NO_DMA,RX_MODE,NULL,UART5,NO_FLAG,NO_FLAG};

extern BSP_USART_Typedef BSP_DMA_USART1_TX;
extern BSP_USART_Typedef BSP_DMA_USART2_TX;
extern BSP_USART_Typedef BSP_DMA_USART3_TX;
extern BSP_USART_Typedef BSP_DMA_UART4_TX;
extern BSP_USART_Typedef BSP_DMA_UART5_TX;

extern BSP_USART_Typedef BSP_DMA_USART1_RX;
extern BSP_USART_Typedef BSP_DMA_USART2_RX;
extern BSP_USART_Typedef BSP_DMA_USART3_RX;
extern BSP_USART_Typedef BSP_DMA_UART4_RX;
extern BSP_USART_Typedef BSP_DMA_UART5_RX;

#endif
